included:
  - Sources
  - Tests

excluded:
  - .build
  - .swiftpm

line_length:
  warning: 120
  error: 150

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 500
  error: 800

function_body_length:
  warning: 60
  error: 100

disabled_rules:
  - trailing_comma
  - opening_brace
  - static_over_final_class

opt_in_rules:
  - empty_count
  - explicit_init
  - closure_spacing
  - sorted_imports
  - redundant_nil_coalescing
